
from pygame import USEREVENT
from pygame.event import Event

EVENT_START = Event(USEREVENT + 1)
EVENT_STOP = Event(USEREVENT + 2)
EVENT_CLEAR = Event(USEREVENT + 3)
EVENT_NEXT = Event(USEREVENT + 4)
EVENT_PATTERNS = Event(USEREVENT + 5)
EVENT_EXIT = Event(USEREVENT + 6)
EVENT_INPUT_MODE_DRAW = Event(USEREVENT + 7)
EVENT_INPUT_MODE_PAN = Event(USEREVENT + 8)